### PR TITLE
Preview rework

### PR DESCRIPTION
**Pull request by lawrencefoley**
Moves the code that extracts the preview image from the a map file from `preview_image_extractor.py` to the `maps` package in the `Preview` class.

### CODE REVIEW

**Comment by lawrencefoley** [comment]
@gynt This is still a WIP.

I did some refactoring of the way the DLL was referenced. I wasn't able to run the individual test with the way that the DLL was referenced... it need the absolute path.

Also, I refactored the `run_tests.py` to use the unit test library instead of `subprocess`.

**Comment by gynt** [comment]
@lawrencefoley great work!

I am fine with it if we merge this with the current master.

Have you checked out the latest version of the compression stuff? I created a no-callback DLL.
Maybe it fixes the issue you are having as well.

**Comment by lawrencefoley** [comment]
@gynt Thank you!

It's still WIP because I wanted to ask if I should just remove the `preview_image_extractor.py` or if it should use the new implementation?

I saw the changes you made with the new DDL; It seems to be working great!

**Comment by gynt** [comment]
For now, I like the separate `preview_image_extractor.py`. It showcases our work (and how it works) better then endless command line arguments for `unpacker.py`.

Hmm, maybe an `examples/` directory is a good idea? It usually contains examples of how to use the software. Maybe you can move a version with the new implementation into there!

**Comment by lawrencefoley** [comment]
@gynt Saw you merged this. Sorry I wasn't able to put in a example script. I've been busy here lately. If it's still needed I can create a new branch for that when I get time.

**Comment by gynt** [comment]
@lawrencefoley No worries, I am busy too! I created a new issue for the examples directory, for future reference :)

**Pull request merged**
